import Header from "@/components/Header";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const gfont = Work_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={gfont.className}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
